### ISSUE TITLE
Not working with playframework Java 2.4.6?

### ISSUE THREAD

**Issue by iAmcR** [adrianhurt/play-bootstrap#44]
The modules directory from the play framework website said that this works for Java or Scala. 

I tried to get this to work in twirl templates in play java framework 2.4.6 and I'm getting compilation errors asking me to change a lot of the parameter types in the field constructors or package.scala files to Java types. 

Could you kindly explain how to fix? 

Thanks.

**Comment by adrianhurt** [comment]
Hi, @iAmcR. Could you give me an example or more details? I always use the Scala version of Play but I'm trying it now with Java and it seems to work, but with a very easy example.

**Comment by iAmcR** [comment]
Hi, @adrianhurt. Yes will do. 

Just to be sure, I used the play-java-intro sample project (http://www.typesafe.com/activator/template/play-java-intro). 

1) I imported the libraries via sbt (build.sbt): 

resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"

libraryDependencies ++= Seq(
  "com.adrianhurt" %% "play-bootstrap" % "1.0-P24-B3-SNAPSHOT",
  "org.webjars" % "font-awesome" % "4.5.0",
  "org.webjars" % "bootstrap-datepicker" % "1.4.0"
)

2) Copied the b3 directory from play24-bootstrap3/module/app/views/b3 (i.e. from the github download) to template's project app/views folder. 

3) Edited the index.scala.html file to be very simple:

@import b3.vertical.fieldConstructor
@()
@main("Welcome to Play") {
    @b3.form(routes.Application.addPerson()) {
        @b3.submit('class -> "btn btn-default"){ Sign in }
    }
}

4) set run (note: sbt compile gives the same error as the following when done from browser)

5) http://localhost:9000 in browser to view app. 

6) This results:

![screen_shot_play24-bootstrap3](https://cloud.githubusercontent.com/assets/16691885/12405082/df8a33e0-be0e-11e5-8aac-47aa040275b1.png)

Notice that it's saying it's requiring Java types...

**Comment by adrianhurt** [comment]
Hi, I'm not have time right now to try this template now, but seeing your steps try to:
* There's no need for "step 2". You don't have to copy manually any code from my github repository. The code is automatically added by "step 1".
* Try this code (or something similar) for "step 3":
```
@()
@import b3.vertical.fieldConstructor
@main("Welcome to Play") {
  @b3.form(routes.Application.addPerson()) {
    @b3.submit('class -> "btn btn-default"){ Add Person }
  }
}
```

**Comment by iAmcR** [comment]
Hi, @adrianhurt 

Changing the example code wasn't the fix. 

However, thanks for pointing out "no need for step 2". I thought it was necessary since I was getting a cannot find package b3 error. I removed it, then did a sbt clean, which seem to fix it for this code. 

I'll try more complex forms and update you. 

Thanks again.

**Comment by adrianhurt** [comment]
Hi @iAmcR, I close the issue, but feel free to reopen or open a new one when you have any other problem.

**Comment by iAmcR** [comment]
Hi, @adrianhurt 

No worries. I actually just started using it on more complicated forms - so far so good. 

Thank you.
